version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - argmax
  - esnya
  - fmax
  - fmin
  - librosa
  - Librosa
  - linspace
  - liujing
  - medfilt
  - nanmax
  - nanmean
  - nanmedian
  - nanmin
  - ndim
  - parselmouth
  - piptrack
  - pyin
  - pyworld
  - rint
  - scipy
  - stonemask
  - unsqueeze
ignoreWords: []
import: []
