version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - argmax
  - esnya
  - fmax
  - fmin
  - librosa
  - Librosa
  - linspace
  - liujing
  - medfilt
  - nanmax
  - nanmean
  - nanmedian
  - nanmin
  - ndim
  - numpy
  - parselmouth
  - piptrack
  - Praat's
  - pyin
  - pyworld
  - rint
  - safetensor
  - scipy
  - stonemask
  - unsqueeze
  - wavfile
ignoreWords: []
import: []
